### ISSUE TITLE
Revamp document submission again

### ISSUE THREAD

**Issue by levitanong** [by-implication/Open-Reconstruction#170]
1. Allow OCD to define required documents for any particular request
   - [x] list down all the submittable documents, but grouped under relevant party. like: "Requester: doc1, doc2, doc3, doc4..."
   - [x] each document has a checkbox to indicate whether or not a document is required
   - [ ] have a list of presets (in a select, maybe) that will automatically check some documents. Can be overridden by manually checking.
   - [x] Allow OCD to change the requirements at any point prior to OCD signoff
   - [ ] Notify relevant parties when requirements have been modified
2. Modify submission interface to accommodate required documents for user viewing the request. (as defined by OCD)
   - [x] one dropzone per required document, plus documents that have already been added prior to OCD making that document non-required
   - [x] one document per dropzone.

**Comment by livtanong** [comment]
lol wontfix
